import { check } from "k6";
import { generateToken, simpanResep } from "../../src/api.js";

export function setup() {
  return {
    token: generateToken().json()["response"]["token"],
  };
}

export default async function (data) {
  // const from = new Date();
  // const to = new Date();
  // to.setDate(to.getDate() - 1);
  // let listPasien = getDaftarAntrianRawatJalan(
  //   { tglAwal: from, tglAkhir: to, jmlRow: 1 },
  //   { token: data.token }
  // );
  // listPasien = listPasien.status === 200 ? listPasien.json() : [];
  const res = simpanResep(
    {
      strukresep: {
        tglresep: "2023-10-11 09:59:28",
        tglregistrasi: "2023-10-11 09:20:14",
        noregistrasi: "2310110002",
        pasienfk: "c7cd51c7-0a68-4695-9ffa-ac0443cadca0",
        nocm: "0000122",
        namapasien: "Sopian R.",
        penulisresepfk: 7,
        ruanganfk: 3,
        noorder: "",
        norecResep: "",
        noresep: "-",
        retur: "-",
        isobatalkes: false,
        isreseppulang: null,
      },
      pelayananpasien: [
        {
          no: 1,
          noregistrasifk: "c7cd51c7-0a68-4695-9ffa-ac0443cadca0",
          generik: null,
          hargajual: "9360",
          jenisobatfk: null,
          jenisobat: null,
          kelasfk: 6,
          stock: "10000",
          harganetto: "7200",
          nostrukterimafk: "OBT-01                              ",
          norec_spd: "OBT-992                             ",
          ruanganfk: 3,
          rke: 1,
          jeniskemasanfk: 2,
          jeniskemasan: "Non Racikan",
          aturanpakaifk: 0,
          aturanpakai: "1x1",
          ispagi: 0,
          issiang: 0,
          issore: 1,
          ismalam: 0,
          routefk: null,
          route: null,
          asalprodukfk: 1,
          asalproduk: "Badan Layanan Umum",
          produkfk: 5991,
          namaproduk: "PARACETAMOL Enema 125 mg/2,5 ml (NP)",
          nilaikonversi: 1,
          satuanstandarfk: 510,
          satuanstandar: "Rectal Tube",
          satuanviewfk: 510,
          satuanview: "Rectal Tube",
          jmlstok: "10000",
          jumlah: 2,
          jumlahobat: 2,
          dosis: 1,
          hargasatuan: "9360",
          hargadiscount: "0",
          persendiscount: 0,
          total: 18720,
          jmldosis: "2/1/125",
          jasa: 0,
          keterangan: null,
          satuanresepfk: null,
          satuanresep: null,
          tglkadaluarsa: "2025-01-31 23:59:59",
          obtkronis: "",
          icon: "fa-inverse lnir lnir-medicine-alt",
          color: "primary",
        },
        {
          no: 2,
          noregistrasifk: "c7cd51c7-0a68-4695-9ffa-ac0443cadca0",
          generik: null,
          hargajual: "589",
          jenisobatfk: null,
          jenisobat: null,
          kelasfk: 6,
          stock: "9980",
          harganetto: "453",
          nostrukterimafk: "OBT-01                              ",
          norec_spd: "OBT-870                             ",
          ruanganfk: 3,
          rke: 2,
          jeniskemasanfk: 2,
          jeniskemasan: "Non Racikan",
          aturanpakaifk: 0,
          aturanpakai: "1x1",
          ispagi: 0,
          issiang: 1,
          issore: 0,
          ismalam: 0,
          routefk: null,
          route: null,
          asalprodukfk: 1,
          asalproduk: "Badan Layanan Umum",
          produkfk: 5869,
          namaproduk: "RISPERIDONE Tab 2 mg (DM)",
          nilaikonversi: 1,
          satuanstandarfk: 184,
          satuanstandar: "Tablet",
          satuanviewfk: 184,
          satuanview: "Tablet",
          jmlstok: "9980",
          jumlah: 1,
          jumlahobat: 1,
          dosis: 1,
          hargasatuan: "589",
          hargadiscount: "0",
          persendiscount: 0,
          total: 589,
          jmldosis: "1/1/2",
          jasa: 0,
          keterangan: null,
          satuanresepfk: null,
          satuanresep: null,
          tglkadaluarsa: "2025-01-31 23:59:59",
          obtkronis: "",
          icon: "fa-inverse lnir lnir-medicine-alt",
          color: "info",
        },
      ],
    },
    { token: data.token }
  );
  check(res, {
    "save-resep is status 201": (r) => r.status === 201,
  });
}
