import { check } from "k6";
import { generateToken, saveEMR } from "../../../src/api.js";
import { uuidv4,randomIntBetween } from "https://jslib.k6.io/k6-utils/1.4.0/index.js";

export function setup() {
  return {
    token: generateToken().json()["response"]["token"],
  };
}

export default function (data) {
  const res = saveEMR(
    {
        "id": "",
        "norec_emr": "",
        "collection": "AsesmenAwalKeperawatanPasienRawatJalan",
        "url_form": "module-emr-profile-pasien-page-emr-asesmen-awal-keperawatan-pasien-rawat-jalan-nurse",
        "name_form": "Assesmen Keperawatan",
        "jenis_emr": "asesmen_medis",
        "data": {
          "kebjamKedatangan": "2024-10-21T08:59:19.425Z",
          "kebjamAsesmenAwal": "2024-10-21T08:59:19.425Z",
          "kebtanggalKedatangan": "2024-10-21T08:59:19.425Z",
          "keadaanumumobgyn": 1,
          "gcse": 4,
          "gcsv": 5,
          "gcsm": 6,
          "kebrujukan": "TIDAK",
          "kebrujuklanjutan": "SENDIRI",
          "kebpilihanallo": 4,
          "keluhanutama": "fghuijoiu",
          "riwayatpenyakit": "0opiygghjk",
          "riwayatpenyakitdahulu": "lkjhgvfvbnm",
          "riwayatpengobatan": "zsxdcfgvhbgtfr",
          "riwayatpenyakitkeluarga": "ytredswzxdcfgvbhj",
          "isalergi": "TIDAK",
          "tekananDarahObgyn": "120/80",
          "nadiObgyn": "30",
          "nafasObgyn": "40",
          "celciusObgyn": "37",
          "sao2Obgyn": "70",
          "beratbadanObgyn": "45",
          "tinggibadanObgyn": "155",
          "nocm": "168513",
          "pasien": {
            "nocm": "168513",
            "nocmfk": "168512",
            "namapasien": "ZAFRAN MIKAIL",
            "tgllahir": "2021-02-25",
            "tempatlahir": "DENPASAR",
            "suku": null,
            "objectjeniskelaminfk": 1,
            "jeniskelamin": "Laki-laki",
            "noidentitas": "5171012502210003",
            "nobpjs": null,
            "statusemr": null,
            "noasuransilain": null,
            "alamatlengkap": "JALAN TUKAD IRAWADI GG.MAHKOTA",
            "kodepos": null,
            "notelepon": null,
            "tglberakhir": "2024-10-22",
            "tglmulai": "2024-10-21",
            "objectkelompokuserfk": "",
            "pegawaipemohonfk": null,
            "nohp": "085965931141",
            "namaayah": null,
            "noregistrasi": "2410210002",
            "namaibu": "ELIK",
            "email": null,
            "objectruanganlastfk": 201,
            "agama": "ISLAM",
            "pendidikan": null,
            "pekerjaan": "Belum/Tidak Bekerja",
            "isfoto": null,
            "objectkebangsaanfk": 1,
            "filename": null,
            "kelompokpasien": "UMUM/PRIBADI",
            "catatan": null,
            "umur": "3thn 7bln 26hr",
            "isFilterProdukLab": "true",
            "enabledEMRSimrsLama": "false",
            "registrasi": {
              "noregistrasi": "2410210002",
              "norec": "3561f89d-6194-436f-92fc-0dc5cda13e8f",
              "isclosing": null,
              "norec_pd": "3561f89d-6194-436f-92fc-0dc5cda13e8f",
              "tglregistrasi": "2024-10-21 15:33:01",
              "tglpulang": "2024-10-21 15:33:01",
              "namadepartemen": "Instalasi Rawat Jalan",
              "kelompokpasien": "UMUM/PRIBADI",
              "asalrujukan": "Datang Sendiri",
              "namaruangan": "POLI INTERNA",
              "namakelas": "NON KELAS",
              "nocmfk": "168512",
              "namarekanan": "Diri Sendiri",
              "dokter": "dr. NI WAYAN INDAH ELYANI, Sp.PD",
              "objectruanganlastfk": 201,
              "objectruanganfk": 201,
              "norec_apd": "84bf2340-2b2a-4b8b-9576-5125346df2fa",
              "objectkelompokpasienlastfk": 1,
              "objectrekananfk": 0,
              "jenispelayanan": 1,
              "jenispelayananfk": 1,
              "objectkelasfk": 6,
              "objectdepartemenfk": 18,
              "objectpegawaifk": 396,
              "nosep": null,
              "inacbg_totalgrouper": null,
              "kdsubspesialisbpjs": "INT",
              "namasubspesialisbpjs": null,
              "dpjplayan_kode": null,
              "dpjplayan_nama": null,
              "tinggibadan": null,
              "beratbadan": null,
              "suhu": null,
              "nadi": null,
              "pernafasan": null,
              "tekanandarah": null,
              "spo2": null,
              "jenispelayananBaru": "REGULER",
              "isberkas": null,
              "apd": {
                "norec_apd": "84bf2340-2b2a-4b8b-9576-5125346df2fa",
                "objectkelasfk": 6,
                "objectruanganfk": 201,
                "namaruangan": "POLI INTERNA",
                "namakelas": "NON KELAS",
                "noregistrasifk": "3561f89d-6194-436f-92fc-0dc5cda13e8f",
                "tglregistrasi": "2024-10-21 15:33:01"
              },
              "billing": 110000,
              "diagnosis": [],
              "laboratorium": [],
              "radiologi": [],
              "isloading": false
            }
          },
          "registrasi": {
            "norec_apd": "84bf2340-2b2a-4b8b-9576-5125346df2fa",
            "norec_pd": "3561f89d-6194-436f-92fc-0dc5cda13e8f",
            "noregistrasi": "2410210002",
            "tglregistrasi": "2024-10-21 15:33:01",
            "kelompokpasien": "UMUM/PRIBADI",
            "asalrujukan": "Datang Sendiri",
            "namarekanan": "Diri Sendiri",
            "namakelas": "NON KELAS",
            "objectruanganfk": 201,
            "tglpulang": "2024-10-21 15:33:01",
            "namaruangan": "POLI INTERNA",
            "dokter": "dr. NI WAYAN INDAH ELYANI, Sp.PD",
            "objectpegawaifk": 396
          }
        }
    },
    { token: data.token }
  );
  check(res, {
    "emr/simpan-emr is status 200": (r) => r.status === 200,
  });
}
