export function table1(): any {
    return [
      [
        { colspan: 7, rowspan: 1, type: 'text-bold', nama: '1. Asesmen Awal' },
      ],
      [
        { colspan: 1, rowspan: 3, type: 'text', nama: 'a. Asesmen medis' },
        { colspan: 1, rowspan: 1, type: 'text', nama: '1. Anamnesa' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'anamnesa1a', value: '1. Anamnesa A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'anamnesa1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'anamnesa1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '2. Pemeriksaan fisik dasar' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'pemeriksaanFisikDasar1a', value: '2. Pemeriksaan fisik dasar A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'pemeriksaanFisikDasar1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'pemeriksaanFisikDasar1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '3. Pemeriksaan obstetri (HIS, DJJ, TFU, VT)' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'pemeriksaanObstetri1a', value: '3. Pemeriksaan obstetri (HIS, DJJ, TFU, VT) A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'pemeriksaanObstetri1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'pemeriksaanObstetri1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 8, type: 'text', nama: 'b. Asesmen kebidanan' },
        { colspan: 1, rowspan: 1, type: 'text', nama: '1. Anamnesis keluhan, riwayat mestruasi, riwayat kehamilan, persalinan dan nifas yang lalu, riwayat kontrasepsi, riwayat kehamilan sekarang, riwayat penyakit keluarga, riwayat operasi, riwayat transfusi darah, riwayat ginekologi, riwayat alergi, riwayat penggunaan obat' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'anamnesisKeluhan1', value: '1. Anamnesis keluhan, riwayat mestruasi, riwayat kehamilan, persalinan dan nifas yang lalu, riwayat kontrasepsi, riwayat kehamilan sekarang, riwayat penyakit keluarga, riwayat operasi, riwayat transfusi darah, riwayat ginekologi, riwayat alergi, riwayat penggunaan obat A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'anamnesisKeluhan1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'anamnesisKeluhan1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '2. Pemeriksaan fisik dan tanda vital' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'pemeriksaanFisik1a', value: '2. Pemeriksaan fisik dan tanda vital A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'pemeriksaanFisik1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'pemeriksaanFisik1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '3. Penilaian skala nyeri' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'penilaianSkalaNyeri1a', value: '3. Penilaian skala nyeri A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'penilaianSkalaNyeri1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'penilaianSkalaNyeri1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '4. Penilaian kondisi psikologi, sosial, ekonomi dan spiritual' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'penilaianKondisiPsikologi1a', value: '4. Penilaian kondisi psikologi, sosial, ekonomi dan spiritual A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'penilaianKondisiPsikologi1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'penilaianKondisiPsikologi1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '5. Kebutuhan informasi dan edukasi' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'kebutuhanInformasi1a', value: '5. Kebutuhan informasi dan edukasi A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'kebutuhanInformasi1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'kebutuhanInformasi1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '6. Skrining nutrisi' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'skriningNutrisi1a', value: '6. Skrining nutrisi A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'skriningNutrisi1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'skriningNutrisi1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '7. Penilaian status fungsional' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'penilaianStatus1a', value: '7. Penilaian status fungsional A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'penilaianStatus1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'penilaianStatus1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '8. Penilaian risiko jatuh' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'penilaianRisikoJatuh1a', value: '8. Penilaian risiko jatuh A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'penilaianRisikoJatuh1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'penilaianRisikoJatuh1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 4, type: 'text-bold', nama: '2. Laboratorium' },
        { colspan: 1, rowspan: 1, type: 'text', nama: '1. DL' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'dL1a', value: '1. DL A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'dL1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'dL1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '2. BT, CT' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'bTCT1a', value: '2. BT, CT A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'bTCT1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'bTCT1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '3. GOLDA' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'golda1a', value: '3. GOLDA A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'golda1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'golda1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '4. Triple eliminasi' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'tripleEliminasi1a', value: '4. Triple eliminasi A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'tripleEliminasi1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'tripleEliminasi1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 2, type: 'text-bold', nama: '3. Radiologi/Imaging' },
        { colspan: 1, rowspan: 1, type: 'text', nama: '1. AT (CTG/NST) (sesuai indikasi)' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'at1a', value: '1. AT (CTG/NST) (sesuai indikasi) A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'at1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'at1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '2. USG (dengan indikasi)' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'usg1a', value: '2. USG (dengan indikasi) A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'usg1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'usg1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 2, type: 'text-bold', nama: '4. Konsultasi' },
        { colspan: 1, rowspan: 1, type: 'text', nama: '1. Anastesi' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'anastesi1a', value: '1. Anastesi A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'anastesi1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'anastesi1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '2. Anak' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'anak1a', value: '2. Anak A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'anak1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'anak1Paraf' },
      ],
      [
        { colspan: 7, rowspan: 1, type: 'text-bold', nama: '5. Asesmen lanjutan' },
      ],
      [
        { colspan: 1, rowspan: 6, type: 'text', nama: 'a. Asesmen medis' },
        { colspan: 1, rowspan: 1, type: 'text', nama: '1. Vital sign' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'vitalSign2b', value: '1. Vital sign B' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'vitalSign2c', value: '1. Vital sign C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'vitalSign2Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'vitalSign2Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '2. Skor nyeri' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'skorNyeri2b', value: '2. Skor nyeri B' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'skorNyeri2c', value: '2. Skor nyeri C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'skorNyeri2Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'skorNyeri2Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '3. TFU' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'TFU2b', value: '3. TFU B' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'TFU2c', value: '3. TFU C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'TFU2Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'TFU2Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '4. Lochia' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'Lochia2b', value: '4. Lochia B' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'Lochia2c', value: '4. Lochia C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'Lochia2Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'Lochia2Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '5. Luka operasi' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'lukaOperasi2b', value: '5. Luka operasi B' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'lukaOperasi2c', value: '5. Luka operasi C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'lukaOperasi2Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'lukaOperasi2Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '6. Produksi ASI' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'produksiASI2b', value: '6. Produksi ASI B' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'produksiASI2c', value: '6. Produksi ASI C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'produksiASI2Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'produksiASI2Paraf' },
      ],
      [
        { colspan: 1, rowspan: 8, type: 'text', nama: 'b. Asesmen kebidanan' },
        { colspan: 1, rowspan: 1, type: 'text', nama: '1. Anamnesis keluhan, riwayat mestruasi, riwayat kehamilan, persalinan dan nifas yang lalu, riwayat kontrasepsi riwayat kehamilan sekarang, riwayat penyakit keluarga, riwayat operasi, riwayat transfusi darah, riwayat ginekologi, riwayat alergi, riwayat penggunaan obat' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'anamnesisKeluhan2a', value: '1. Anamnesis keluhan, riwayat mestruasi, riwayat kehamilan, persalinan dan nifas yang lalu, riwayat kontrasepsi riwayat kehamilan sekarang, riwayat penyakit keluarga, riwayat operasi, riwayat transfusi darah, riwayat ginekologi, riwayat alergi, riwayat penggunaan obat A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'anamnesisKeluhan2Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'anamnesisKeluhan2Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '2. Pemeriksaan fisik dan tanda vital' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'pemeriksaanFisik2a', value: '2. Pemeriksaan fisik dan tanda vital A' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'pemeriksaanFisik2b', value: '2. Pemeriksaan fisik dan tanda vital B' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'pemeriksaanFisik2c', value: '2. Pemeriksaan fisik dan tanda vital C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'pemeriksaanFisik2Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'pemeriksaanFisik2Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '3. Penilaian skala nyeri' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'penilaianSkalaNyeri2a', value: '3. Penilaian skala nyeri A' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'penilaianSkalaNyeri2b', value: '3. Penilaian skala nyeri B' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'penilaianSkalaNyeri2c', value: '3. Penilaian skala nyeri C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'penilaianSkalaNyeri2Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'penilaianSkalaNyeri2Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '4. Penilaian kondisi psikologi, sosial, ekonomi dan spiritual' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'penilaianKondisiPsikologi2a', value: '4. Penilaian kondisi psikologi, sosial, ekonomi dan spiritual A' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'penilaianKondisiPsikologi2b', value: '4. Penilaian kondisi psikologi, sosial, ekonomi dan spiritual B' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'penilaianKondisiPsikologi2c', value: '4. Penilaian kondisi psikologi, sosial, ekonomi dan spiritual C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'penilaianKondisiPsikologi2Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'penilaianKondisiPsikologi2Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '5. Kebutuhan informasi dan edukasi' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'kebutuhanInformasiDanEdukasi2a', value: '5. Kebutuhan informasi dan edukasi A' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'kebutuhanInformasiDanEdukasi2b', value: '5. Kebutuhan informasi dan edukasi B' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'kebutuhanInformasiDanEdukasi2c', value: '5. Kebutuhan informasi dan edukasi C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'kebutuhanInformasiDanEdukasi2Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'kebutuhanInformasiDanEdukasi2Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '6. Skrining nutrisi' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'skriningNutrisi2a', value: '6. Skrining nutrisi A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'skriningNutrisi2Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'skriningNutrisi2Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '7. Penilaian status fungsional' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'penilaianStatusFungsional2a', value: '7. Penilaian status fungsional A' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'penilaianStatusFungsional2b', value: '7. Penilaian status fungsional B' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'penilaianStatusFungsional2c', value: '7. Penilaian status fungsional C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'penilaianStatusFungsional2Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'penilaianStatusFungsional2Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '8. Penilaian risiko jatuh' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'penilaianRisikoJatuh2a', value: '8. Penilaian risiko jatuh A' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'penilaianRisikoJatuh2b', value: '8. Penilaian risiko jatuh B' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'penilaianRisikoJatuh2c', value: '8. Penilaian risiko jatuh C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'penilaianRisikoJatuh2Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'penilaianRisikoJatuh2Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: 'c. Asesmen gizi' },
        { colspan: 1, rowspan: 1, type: 'text', nama: 'Melanjutkan hasil screening perawat terkait risiko malnutrisi dan atau kondisi khusus. Maka akan dilakukan asesmen gizi oleh dietisien/nutrisionis' },
        { colspan: 1, rowspan: 1, type: 'kosong'},
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'hasilScreeningPerawat2b', value: 'Melanjutkan hasil screening perawat terkait risiko malnutrisi dan atau kondisi khusus. Maka akan dilakukan asesmen gizi oleh dietisien/nutrisionis B' },
        { colspan: 1, rowspan: 1, type: 'kosong'},
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'hasilScreeningPerawat2Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'hasilScreeningPerawat2Paraf' },
      ],
      [
        { colspan: 7, rowspan: 1, type: 'text-bold', nama: '6. Diagnosis' },
      ],
      [
        { colspan: 1, rowspan: 2, type: 'text', nama: 'a. Diagnosa medis' },
        { colspan: 1, rowspan: 1, type: 'text', nama: '1. Hamil Aterm Indikasi Sectio Cesaria Tanpa Tanda-tanda Infeksi' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'hamilAtermIndikasi1a', value: '1. Hamil Aterm Indikasi Sectio Cesaria Tanpa Tanda-tanda Infeksi A' },
        { colspan: 1, rowspan: 1, type: 'kosong'},
        { colspan: 1, rowspan: 1, type: 'kosong'},
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'hamilAtermIndikasi1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'hamilAtermIndikasi1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '2. Post SC' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'postSC1a', value: '2. Post SC A' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'postSC1b', value: '2. Post SC B' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'postSC1c', value: '2. Post SC C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'postSC1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'postSC1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 2, type: 'text', nama: 'b. Diagnosis kebidanan' },
        { colspan: 1, rowspan: 1, type: 'text', nama: '1. Hamil Aterm Indikasi Sectio Cesaria Tanpa Tanda-tanda Infeksi' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'hamilAtermIndikasi2a', value: '1. Hamil Aterm Indikasi Sectio Cesaria Tanpa Tanda-tanda Infeksi A' },
        { colspan: 1, rowspan: 1, type: 'kosong'},
        { colspan: 1, rowspan: 1, type: 'kosong'},
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'hamilAtermIndikasi2Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'hamilAtermIndikasi2Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '2. Post SC' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'postSC2a', value: '2. Post SC A' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'postSC2b', value: '2. Post SC B' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'postSC2c', value: '2. Post SC C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'postSC2Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'postSC2Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: 'c. Diagnosis Gizi' },
        { colspan: 1, rowspan: 1, type: 'text', nama: '(NI.5.1) Peningkatan kebutuhan energi dan protein berkaitan dengan peningkatnya kebutuhan saat melahirkan dan ibu menyusui ditandai dengan adanya post sectio cesaria' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'peningkatanKebutuhanEnergi1b', value: '(NI.5.1) Peningkatan kebutuhan energi dan protein berkaitan dengan peningkatnya kebutuhan saat melahirkan dan ibu menyusui ditandai dengan adanya post sectio cesaria B' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'peningkatanKebutuhanEnergi1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'peningkatanKebutuhanEnergi1Paraf' },
      ],
      [
        { colspan: 7, rowspan: 1, type: 'text-bold', nama: '7. Discharge Planning & Edukasi Terintegrasi (Selama perawatan)' },
      ],
      [
        { colspan: 1, rowspan: 7, type: 'text', nama: 'a. Edukasi/informasi medis (sesuai kasus)' },
        { colspan: 1, rowspan: 1, type: 'text', nama: '1. Penjelasan diagnosis' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'penjelasanDiagnosis1a', value: '1. Penjelasan diagnosis A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'penjelasanDiagnosis1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'penjelasanDiagnosis1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '2. Rencana terapi' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'rencanaTerapi1a', value: '2. Rencana terapi A' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'rencanaTerapi1b', value: '2. Rencana terapi B' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'rencanaTerapi1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'rencanaTerapi1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '3. Informed consent' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'informedConsent1a', value: '3. Informed consent A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'informedConsent1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'informedConsent1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '4. IMD' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'iMD1a', value: '4. IMD A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'iMD1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'iMD1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '5. SHK' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'sHK1a', value: '5. SHK A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'sHK1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'sHK1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '6. Kontrasepsi' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'kontrasepsi1a', value: '6. Kontrasepsi A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'kontrasepsi1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'kontrasepsi1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '7. ASI Eksklusif' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'aSIEksklusif1a', value: '7. ASI Eksklusif A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'aSIEksklusif1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'aSIEksklusif1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: 'b. Edukasi & konseling gizi (sesuai kasus)' },
        { colspan: 1, rowspan: 1, type: 'text', nama: 'Penjelasan mengenai pemberian makanan diet Tinggi Energi Tinggi Protein (TETP), jadwal makan rumah sakit dan risiko kontaminasi makanan' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'mengenaiPemberianMakanan1b', value: 'Penjelasan mengenai pemberian makanan diet Tinggi Energi Tinggi Protein (TETP), jadwal makan rumah sakit dan risiko kontaminasi makanan B' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'mengenaiPemberianMakanan1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'mengenaiPemberianMakanan1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 6, type: 'text', nama: 'c. Edukasi kebidanan (sesuai kasus)' },
        { colspan: 1, rowspan: 1, type: 'text', nama: '1. Penjelasan hasil pemeriksaan dan tindakan yang akan dilakukan serta risiko yang mungkin terjadi' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'penjelasanHasilPemeriksaan1a', value: '1. Penjelasan hasil pemeriksaan dan tindakan yang akan dilakukan serta risiko yang mungkin terjadi A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'penjelasanHasilPemeriksaan1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'penjelasanHasilPemeriksaan1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '2. Tanda-tanda bahaya nifas' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'tandaBahayaNifas1a', value: '2. Tanda-tanda bahaya nifas A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'tandaBahayaNifas1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'tandaBahayaNifas1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '3. Perawatan payudara dan menyusui' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'perawatanPayudara1a', value: '3. Perawatan payudara dan menyusui A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'perawatanPayudara1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'perawatanPayudara1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '4. Perawatan luka post operasi' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'perawatanLukaPostOperasi1c', value: '4. Perawatan luka post operasi C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'perawatanLukaPostOperasi1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'perawatanLukaPostOperasi1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '5. Perawatan bayi baru lahir' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'perawatanBayiBaruLahir1c', value: '5. Perawatan bayi baru lahir C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'perawatanBayiBaruLahir1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'perawatanBayiBaruLahir1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '6. Vulva hygiene' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'vulvaHygiene1c', value: '6. Vulva hygiene C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'vulvaHygiene1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'vulvaHygiene1Paraf' },
      ],
      [
        { colspan: 7, rowspan: 1, type: 'text-bold', nama: '8. Terapi' },
      ],
      [
        { colspan: 1, rowspan: 3, type: 'text', nama: 'a. Injeksi' },
        { colspan: 1, rowspan: 1, type: 'text', nama: '1. Antibiotika profilaksis Cefazolin inj 2 gr (IV), 30 menit sebelum incisi' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'antibiotikaProfilaksisCefazolin1a', value: '1. Antibiotika profilaksis Cefazolin inj 2 gr (IV), 30 menit sebelum incisi A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'antibiotikaProfilaksisCefazolin1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'antibiotikaProfilaksisCefazolin1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '2. Oksitosin 10 IU' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'oksitosin1a', value: '2. Oksitosin 10 IU A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'oksitosin1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'oksitosin1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '3. Methil ergometrim IV 1 ampul (0,2 mg)' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'methilErgometrimIV1a', value: '3. Methil ergometrim IV 1 ampul (0,2 mg) A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'methilErgometrimIV1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'methilErgometrimIV1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 2, type: 'text', nama: 'b. Cairan infus' },
        { colspan: 1, rowspan: 1, type: 'text', nama: '1. Koloid' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'koloid1a', value: '1. Koloid A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'koloid1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'koloid1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '2. RL+ Drip oksitosin 20 IU 28 tpm s/d 12 jam post SC' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'rLDripOksitosin1a', value: '2. RL+ Drip oksitosin 20 IU 28 tpm s/d 12 jam post SC A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'rLDripOksitosin1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'rLDripOksitosin1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 5, type: 'text', nama: 'c. Obat oral' },
        { colspan: 1, rowspan: 1, type: 'text', nama: '1. Cefadroxil 3 X 500 mg' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'cefadroxil3X5001a', value: '1. Cefadroxil 3 X 500 mg A' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'cefadroxil3X5001b', value: '1. Cefadroxil 3 X 500 mg B' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'cefadroxil3X5001c', value: '1. Cefadroxil 3 X 500 mg C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'cefadroxil3X5001Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'cefadroxil3X5001Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '2. Paracetamol 3 X 500mg' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'paracetamol3X5001b', value: '2. Paracetamol 3 X 500mg B' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'paracetamol3X5001c', value: '2. Paracetamol 3 X 500mg C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'paracetamol3X5001Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'paracetamol3X5001Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '3. Natrium diclofenac 3 X 50mg' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'natriumDiclofenac3X501b', value: '3. Natrium diclofenac 3 X 50mg B' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'natriumDiclofenac3X501c', value: '3. Natrium diclofenac 3 X 50mg C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'natriumDiclofenac3X501Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'natriumDiclofenac3X501Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '4. Methil ergometrin 3 X 0,125 mg' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'methilErgometrin3X01251b', value: '4. Methil ergometrin 3 X 0,125 mg B' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'methilErgometrin3X01251c', value: '4. Methil ergometrin 3 X 0,125 mg C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'methilErgometrin3X01251Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'methilErgometrin3X01251Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '5. Vitamin A200.000 IU' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'vitaminA200000IU1b', value: '5. Vitamin A200.000 IU B' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'vitaminA200000IU1c', value: '5. Vitamin A200.000 IU C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'vitaminA200000IU1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'vitaminA200000IU1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 7, type: 'text', nama: 'd. Obat anastesi' },
        { colspan: 1, rowspan: 1, type: 'text', nama: '1. Spinal Anastesi' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'spinalAnastesi1a', value: '1. Spinal Anastesi A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'spinalAnastesi1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'spinalAnastesi1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '2. Fentanyl continous (Drip/infuse pump/PCA) / Petidine 100 mg' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'fentanylContinous1a', value: '2. Fentanyl continous (Drip/infuse pump/PCA) / Petidine 100 mg A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'fentanylContinous1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'fentanylContinous1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '3. Midazolam 5 mg' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'midazolam5mg1a', value: '3. Midazolam 5 mg A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'midazolam5mg1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'midazolam5mg1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '4. Bupivacain 0,5% heavy' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'bupivacain05Heavy1a', value: '4. Bupivacain 0,5% heavy A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'bupivacain05Heavy1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'bupivacain05Heavy1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '5. Ketorolak 2 X 30 mg iv' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'ketorolak2X30mgiv1a', value: '5. Ketorolak 2 X 30 mg iv A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'ketorolak2X30mgiv1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'ketorolak2X30mgiv1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '6. Ondancentron 4 mg' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'ondancentron4mg1a', value: '6. Ondancentron 4 mg A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'ondancentron4mg1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'ondancentron4mg1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '7. Efedrine 50 mg' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'efedrine50mg1a', value: '7. Efedrine 50 mg A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'efedrine50mg1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'efedrine50mg1Paraf' },
      ],
      [
        { colspan: 7, rowspan: 1, type: 'text-bold', nama: '9. Tata Laksana/Intervensi (sesuai kasus) selama perawatan' },
      ],
      [
        { colspan: 1, rowspan: 2, type: 'text', nama: 'a. TLI Medis' },
        { colspan: 1, rowspan: 1, type: 'text', nama: '1. Sectio Cesaria' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'sectioCesaria1a', value: '1. Sectio Cesaria A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'sectioCesaria1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'sectioCesaria1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '2. Rawat luka' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'rawatLuka1c', value: '2. Rawat luka C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'rawatLuka1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'rawatLuka1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 10, type: 'text', nama: 'b. TLI Kebidanan' },
        { colspan: 1, rowspan: 1, type: 'text', nama: '1. Membimbing teknik relaksasi dan pendampingan' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'membimbingTeknikRelaksasiDanPendampingan1a', value: '1. Membimbing teknik relaksasi dan pendampingan A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'membimbingTeknikRelaksasiDanPendampingan1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'membimbingTeknikRelaksasiDanPendampingan1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '2. Melakukan persiapan operasi' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'melakukanPersiapanOperasi1a', value: '2. Melakukan persiapan operasi A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'melakukanPersiapanOperasi1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'melakukanPersiapanOperasi1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '3. Rawat gabung' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'rawatGabung1a', value: '3. Rawat gabung A' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'rawatGabung1b', value: '3. Rawat gabung B' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'rawatGabung1c', value: '3. Rawat gabung C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'rawatGabung1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'rawatGabung1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '4. Membimbing menyusui' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'membimbingMenyusui1b', value: '4. Membimbing menyusui B' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'membimbingMenyusui1c', value: '4. Membimbing menyusui C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'membimbingMenyusui1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'membimbingMenyusui1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '5. Membimbing cara masase uterus' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'membimbingCaraMasaseUterus1b', value: '5. Membimbing cara masase uterus B' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'membimbingCaraMasaseUterus1c', value: '5. Membimbing cara masase uterus C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'membimbingCaraMasaseUterus1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'membimbingCaraMasaseUterus1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '6. Membimbing mobilisasi dini' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'membimbingMobilisasiDini1b', value: '6. Membimbing mobilisasi dini B' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'membimbingMobilisasiDini1c', value: '6. Membimbing mobilisasi dini C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'membimbingMobilisasiDini1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'membimbingMobilisasiDini1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '7. Eliminasi' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'eliminasi1b', value: '7. Eliminasi B' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'eliminasi1c', value: '7. Eliminasi C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'eliminasi1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'eliminasi1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '8. Personal hygiene' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'personalHygiene1b', value: '8. Personal hygiene B' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'personalHygiene1c', value: '8. Personal hygiene C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'personalHygiene1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'personalHygiene1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '9. Perawatan payudara' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'perawatanPayudara1b', value: '9. Perawatan payudara B' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'perawatanPayudara1c', value: '9. Perawatan payudara C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'perawatanPayudara1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'perawatanPayudara1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '10. Perawatan luka post operasi' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'perawatanLukaPostOperasi1c', value: '10. Perawatan luka post operasi C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'perawatanLukaPostOperasi1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'perawatanLukaPostOperasi1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 7, type: 'text', nama: 'c. TLI Gizi' },
        { colspan: 1, rowspan: 1, type: 'text', nama: '1. Tujuan diet :' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'tujuanDiet1b', value: '1. Tujuan diet : B' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 7, type: 'textarea', nama: 'TLIGizi1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'tujuanDiet1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: 'a. Memenuhi kebutuhan gizi' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'memenuhiKebutuhanGizi1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '2. Preskripsi diet :' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'preskripsiDiet1b', value: '2. Preskripsi diet : B' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'preskripsiDiet1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: 'a. Jenis diet yang diberikan diet Tinggi Energi Tinggi Protein' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'dietYangDiberikanDietTinggi1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: 'b. Kebutuhan gizi sesuai umur, jenis kelamin, tinggi badan dan berat badan' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'kebutuhanGiziSesuaiUmur1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: 'c. Bentuk makanan : biasa' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'bentukMakananBiasa1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: 'd. Jalur pemberian : oral' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'jalurPemberianOral1Paraf' },
      ],
      [
        { colspan: 7, rowspan: 1, type: 'text-bold', nama: '10. Mobilisasi/Rehabilitasi (sesuai kasus) selama perawatan' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: 'a. Medis' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'medis1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'medis1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: 'b. Kebidanan' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'kebidanan1a', value: 'b. Kebidanan A' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'kebidanan1b', value: 'b. Kebidanan B' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'kebidanan1c', value: 'b. Kebidanan C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'kebidanan1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'kebidanan1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: 'c. Fisioterapi' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'fisioterapi1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'fisioterapi1Paraf' },
      ],
      [
        { colspan: 7, rowspan: 1, type: 'text-bold', nama: '11. Outcome/hasil(selama perawatan)' },
      ],
      [
        { colspan: 1, rowspan: 7, type: 'text', nama: 'a. Medis' },
        { colspan: 1, rowspan: 1, type: 'text', nama: '1. Operasi selesai dalam 1 jam' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'operasiSelesaiDalam1Jam1a', value: '1. Operasi selesai dalam 1 jam A' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'operasiSelesaiDalam1Jam1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'operasiSelesaiDalam1Jam1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '2. Perdarahan < 1000 cc' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'Perdarahan1000cc1a', value: '2. Perdarahan < 1000 cc A' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'Perdarahan1000cc1b', value: '2. Perdarahan < 1000 cc B' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'Perdarahan1000cc1c', value: '2. Perdarahan < 1000 cc C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'Perdarahan1000cc1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'Perdarahan1000cc1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '3. Komplikasi tindakan (-)' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'komplikasiTindakan1a', value: '3. Komplikasi tindakan (-) A' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'komplikasiTindakan1b', value: '3. Komplikasi tindakan (-) B' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'komplikasiTindakan1c', value: '3. Komplikasi tindakan (-) C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'komplikasiTindakan1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'komplikasiTindakan1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '4. Tanda/gejala ILO (-)' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'tandaGejalaILO1a', value: '4. Tanda/gejala ILO (-) A' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'tandaGejalaILO1b', value: '4. Tanda/gejala ILO (-) B' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'tandaGejalaILO1c', value: '4. Tanda/gejala ILO (-) C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'tandaGejalaILO1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'tandaGejalaILO1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '5. Dapat mobilisasi dan menyusui tanpa bantuan' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'dapatMobilisasiDanMenyusui1a', value: '5. Dapat mobilisasi dan menyusui tanpa bantuan A' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'dapatMobilisasiDanMenyusui1b', value: '5. Dapat mobilisasi dan menyusui tanpa bantuan B' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'dapatMobilisasiDanMenyusui1c', value: '5. Dapat mobilisasi dan menyusui tanpa bantuan C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'dapatMobilisasiDanMenyusui1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'dapatMobilisasiDanMenyusui1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '6. Nifas baik' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'nifasBaik1a', value: '6. Nifas baik A' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'nifasBaik1b', value: '6. Nifas baik B' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'nifasBaik1c', value: '6. Nifas baik C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'nifasBaik1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'nifasBaik1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '7. Nyeri terkontrol dengan obat oral' },
        { colspan: 1, rowspan: 1, type: 'kosong' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'nyeriTerkontrolDenganObatOral1b', value: '7. Nyeri terkontrol dengan obat oral B' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'nyeriTerkontrolDenganObatOral1c', value: '7. Nyeri terkontrol dengan obat oral C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'nyeriTerkontrolDenganObatOral1Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'nyeriTerkontrolDenganObatOral1Paraf' },
      ],
      [
        { colspan: 1, rowspan: 4, type: 'text', nama: 'b. Kebidanan' },
        { colspan: 1, rowspan: 1, type: 'text', nama: '1. Perdarahan < 1000 cc' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'perdarahan1000cc2a', value: '1. Perdarahan < 1000 cc A' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'perdarahan1000cc2b', value: '1. Perdarahan < 1000 cc B' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'perdarahan1000cc2c', value: '1. Perdarahan < 1000 cc C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'perdarahan1000cc2Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'perdarahan1000cc2Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '2. Komplikasi tindakan (-)' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'komplikasiTindakan2a', value: '2. Komplikasi tindakan (-) A' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'komplikasiTindakan2b', value: '2. Komplikasi tindakan (-) B' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'komplikasiTindakan2c', value: '2. Komplikasi tindakan (-) C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'komplikasiTindakan2Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'komplikasiTindakan2Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '3. Nifas baik' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'nifasBaik2a', value: '3. Nifas baik A' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'nifasBaik2b', value: '3. Nifas baik B' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'nifasBaik2c', value: '3. Nifas baik C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'nifasBaik2Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'nifasBaik2Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: '4. Dapat mobilisasi dan menyusui tanpa bantuan' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'dapatMobilisasiDanMenyusui2a', value: '4. Dapat mobilisasi dan menyusui tanpa bantuan A' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'dapatMobilisasiDanMenyusui2b', value: '4. Dapat mobilisasi dan menyusui tanpa bantuan B' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'dapatMobilisasiDanMenyusui2c', value: '4. Dapat mobilisasi dan menyusui tanpa bantuan C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'dapatMobilisasiDanMenyusui2Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'dapatMobilisasiDanMenyusui2Paraf' },
      ],
      [
        { colspan: 1, rowspan: 1, type: 'text', nama: 'c. Gizi' },
        { colspan: 1, rowspan: 1, type: 'text', nama: 'Asupan makan ≥ 80%' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'asupanMakan801a', value: 'Asupan makan ≥ 80% A' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'asupanMakan801b', value: 'Asupan makan ≥ 80% B' },
        { colspan: 1, rowspan: 1, type: 'checkbox', nama: 'asupanMakan801c', value: 'Asupan makan ≥ 80% C' },
        { colspan: 1, rowspan: 1, type: 'textarea', nama: 'asupanMakan801Text' },
        { colspan: 1, rowspan: 1, type: 'combobox_perawat', nama: 'asupanMakan801Paraf' },
      ],
    ]
  }